//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.UserMsg", typeof(UserMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xảy ra lỗi trong quá trình thêm, vui lòng thử lại sau hoặc liên hệ Thắng để được hỗ trợ.
        /// </summary>
        internal static string AddErr {
            get {
                return ResourceManager.GetString("AddErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công.
        /// </summary>
        internal static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra,vui lòng thử lại hoặc liên hệ Thắng để được trợ giúp.
        /// </summary>
        internal static string CommonErrr {
            get {
                return ResourceManager.GetString("CommonErrr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code không được phép trông.
        /// </summary>
        internal static string CustomerCodeCannotBeNull {
            get {
                return ResourceManager.GetString("CustomerCodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không tồn tại.
        /// </summary>
        internal static string CustomerCodeDoesNotExist {
            get {
                return ResourceManager.GetString("CustomerCodeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được trùng.
        /// </summary>
        internal static string CustomerCodeDuplicate {
            get {
                return ResourceManager.GetString("CustomerCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm mã khách hàng này không tồn tại, vui lòng kiểm tra lại.
        /// </summary>
        internal static string CustomerGroupDoesNotExist {
            get {
                return ResourceManager.GetString("CustomerGroupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Nhóm khách hàng đã tồn tại.
        /// </summary>
        internal static string CustomerGroupIdDuplicate {
            get {
                return ResourceManager.GetString("CustomerGroupIdDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm mã khách hàng không được để trống.
        /// </summary>
        internal static string CustomerGroupNameCouldNotBeNull {
            get {
                return ResourceManager.GetString("CustomerGroupNameCouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định danh khách hàng không được trùng.
        /// </summary>
        internal static string CustomerIdDuplicate {
            get {
                return ResourceManager.GetString("CustomerIdDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy khách hàng trong hệ thống.
        /// </summary>
        internal static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong quá trình xóa, vui lòng thử lại sau hoặc liên hệ Thắng để được hỗ trợ.
        /// </summary>
        internal static string DeleteErr {
            get {
                return ResourceManager.GetString("DeleteErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        internal static string DeleteSucess {
            get {
                return ResourceManager.GetString("DeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được trùng.
        /// </summary>
        internal static string EmailDuplicate {
            get {
                return ResourceManager.GetString("EmailDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không tồn tại.
        /// </summary>
        internal static string EmployeeCodeDoesNotExist {
            get {
                return ResourceManager.GetString("EmployeeCodeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được trùng.
        /// </summary>
        internal static string EmployeeCodeDuplicate {
            get {
                return ResourceManager.GetString("EmployeeCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định danh nhân viên không được trùng.
        /// </summary>
        internal static string EmployeeIdDuplicate {
            get {
                return ResourceManager.GetString("EmployeeIdDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống.
        /// </summary>
        internal static string EmployeeNameCannotBeNull {
            get {
                return ResourceManager.GetString("EmployeeNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không tồn tại.
        /// </summary>
        internal static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm mã khách hàng không hợp lệ.
        /// </summary>
        internal static string File_CustomerGroupInvalid {
            get {
                return ResourceManager.GetString("File_CustomerGroupInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh sai định dạng.
        /// </summary>
        internal static string File_DobInvalid {
            get {
                return ResourceManager.GetString("File_DobInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã tồn tại trên tệp nhập khẩu.
        /// </summary>
        internal static string File_DuplicateCustomerCode {
            get {
                return ResourceManager.GetString("File_DuplicateCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã tồn tại .
        /// </summary>
        internal static string File_DuplicatePhoneNumber {
            get {
                return ResourceManager.GetString("File_DuplicatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không được để trống.
        /// </summary>
        internal static string FileNotValid {
            get {
                return ResourceManager.GetString("FileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi trong quá trình tìm kiếm, vui lòng liên hệ Thắng hoặc thử lại sau.
        /// </summary>
        internal static string FoundErr {
            get {
                return ResourceManager.GetString("FoundErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào trong cơ sở dữ liệu.
        /// </summary>
        internal static string GetEmpty {
            get {
                return ResourceManager.GetString("GetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy ra không thành công, vui lòng thử lại sau hoặc liên hệ Thắng để được hỗ trợ.
        /// </summary>
        internal static string GetErr {
            get {
                return ResourceManager.GetString("GetErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy thành công.
        /// </summary>
        internal static string GetSuccess {
            get {
                return ResourceManager.GetString("GetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang phải &gt;0.
        /// </summary>
        internal static string PagingErr {
            get {
                return ResourceManager.GetString("PagingErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được trùng.
        /// </summary>
        internal static string PhoneNumberDuplicate {
            get {
                return ResourceManager.GetString("PhoneNumberDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí này không tồn tại, vui lòng chọn vị trí khác.
        /// </summary>
        internal static string PositionIdDoesntExist {
            get {
                return ResourceManager.GetString("PositionIdDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong quá trình cập nhật, vui lòng thử lại sau hoặc liên hệ Thắng để được hỗ trợ.
        /// </summary>
        internal static string UpdateErr {
            get {
                return ResourceManager.GetString("UpdateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file không thành công, vui lòng liên hệ Thắng để được hỗ trợ.
        /// </summary>
        internal static string UpLoadFailed {
            get {
                return ResourceManager.GetString("UpLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file thành công.
        /// </summary>
        internal static string UploadSuccess {
            get {
                return ResourceManager.GetString("UploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File phải đúng định dạng .xlsx.
        /// </summary>
        internal static string Wrong_File_format {
            get {
                return ResourceManager.GetString("Wrong File format", resourceCulture);
            }
        }
    }
}
